[services.Cloudflare-ECH]
type = "url"
v4_url = "https://www.cloudflare.com/ips-v4"
v6_url = "https://www.cloudflare.com/ips-v6"

[services.Discord]
type = "url"
v4_url = "https://iplist.opencck.org/?format=text&data=cidr4&site=discord.gg&site=discord.media"
v6_url = "https://iplist.opencck.org/?format=text&data=cidr6&site=discord.gg&site=discord.media"

[services.Telegram]
type = "single_url"
url = "https://core.telegram.org/resources/cidr.txt"

[services.Meta]
type = "asn"
asn = 32934

[services.X-Twitter]
type = "asn"
asn = 13414

[services.Hetzner]
type = "asn"
asn = 24940

[services.OVH]
type = "asn"
asn = 16276

[services.Amazon]
type = "asn"
asn = 16509

[settings]
summary = ["Cloudflare-ECH", "Meta", "X-Twitter"]
bgp_url = "https://bgp.tools/table.txt"
user_agent = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36"
