[services.Telegram]
v2fly = "telegram"
general = "false"
[services.YouTube]
v2fly = "youtube"
[services.TikTok]
v2fly = "tiktok"
[services."X"]
url = "https://iplist.opencck.org/?format=text&data=domains&site=x.com&site=grok.com"
v2fly = "x"
[services."Discord"]
url = "https://iplist.opencck.org/?format=text&data=domains&site=discord.com&site=discord.gg&site=discord.media"
v2fly = "discord"
[services.SuperCell]
v2fly = "supercell"
[services.OpenAI]
v2fly = "openai"
[services.Anthropic]
v2fly = "anthropic"
[services.Instagram]
v2fly = "instagram"
[services.Spotify]
v2fly = "spotify"
[services.SoundCloud]
v2fly = "SoundCloud"
