[services.Telegram]
v2fly = "telegram"
general = "false"
[services.YouTube]
url = ["https://iplist.opencck.org/?format=text&data=domains&site=youtube.com", "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Services/youtube.lst"]
v2fly = "youtube"
[services.TikTok]
v2fly = "tiktok"
[services."X"]
url = "https://iplist.opencck.org/?format=text&data=domains&site=x.com&site=grok.com"
v2fly = "x"
[services."Discord"]
url = "https://iplist.opencck.org/?format=text&data=domains&site=discord.com&site=discord.gg&site=discord.media"
v2fly = "discord"
[services.SuperCell]
v2fly = "supercell"
[services.OpenAI]
v2fly = "openai"
[services.Anthropic]
v2fly = "anthropic"
[services.Meta]
v2fly = "meta"
[services.WhatsApp]
v2fly = "whatsapp"
general = "false"
[services.Spotify]
v2fly = "spotify"
[services.SoundCloud]
v2fly = "SoundCloud"
[services.HDRezka]
url = "https://iplist.opencck.org/?format=text&data=domains&site=hdrezka.ag"
[services.AWS]
v2fly = "aws"
general = "false"
[services.Viber]
url = "https://iplist.opencck.org/?format=text&data=domains&site=viber.com"
v2fly = "viber"
general = "false"
[groups.RU-Media]
url = ["https://iplist.opencck.org/?format=text&data=domains&site=agents.media&site=agentura.ru&site=bbc.com&site=bellingcat.com&site=cherta.media&site=colta.ru&site=currenttime.tv&site=dept.one&site=doxa.team&site=dw.com&site=echofm.online&site=ehorussia.com&site=ej.ru&site=euronews.com&site=exler.ru&site=golosameriki.com&site=gordonua.com&site=gulagu.net&site=holod.media&site=hrw.org&site=istories.media&site=kasparov.ru&site=kavkaz-uzel.eu&site=korrespondent.net&site=krymr.com&site=meduza.io&site=memohrc.org&site=moscowtimes.ru&site=navalny.com&site=newtimes.ru&site=novayagazeta.ru&site=ovd.info&site=paperpaper.ru&site=polit.ru&site=proekt.media&site=prostovpn.org&site=radiosvoboda.org&site=semnasem.org&site=svoboda.org&site=tayga.info&site=the-village.ru&site=theins.ru&site=thetruestory.news&site=tvrain.ru&site=unian.net&site=verstka.media&site=vot-tak.tv&site=zona.media", "https://raw.githubusercontent.com/itdoginfo/allow-domains/refs/heads/main/Categories/news.lst"]
v2fly = "category-media-ru"