name: Update Block Lists

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    paths:
      - 'categories/Block/**.lst'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          mkdir -p categories/Block
          touch categories/Block/block-ips.lst categories/Block/block-domains.lst

      - name: Validate and fix entries
        id: validate
        run: |
          cd categories/Block
          # Извлекаем ошибочные записи
          grep -E '^[^0-9]' block-ips.lst > domains.tmp || true
          grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' block-domains.lst > ips.tmp || true
          
          # Перемещаем найденные записи
          if [ -s domains.tmp ]; then
            cat domains.tmp >> block-domains.lst
            grep -v -f domains.tmp block-ips.lst > temp && mv temp block-ips.lst
          fi
          
          if [ -s ips.tmp ]; then
            cat ips.tmp >> block-ips.lst
            grep -v -f ips.tmp block-domains.lst > temp && mv temp block-domains.lst
          fi
          
          rm -f domains.tmp ips.tmp
          echo "fixed=$(( $(wc -l < block-ips.lst) + $(wc -l < block-domains.lst) ))" >> $GITHUB_OUTPUT

      - name: Fetch external data
        run: |
          curl -s https://raw.githubusercontent.com/Ruddernation-Designs/Adobe-URL-Block-List/master/hosts  \
            | grep -v '^#' \
            | sed 's/^0.0.0.0 *//' \
            | grep -v '^$' > temp.txt

      - name: Update lists
        run: |
          cd categories/Block
          # Используем абсолютный путь к temp.txt
          grep -E '^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$' "$GITHUB_WORKSPACE/temp.txt" >> block-ips.lst
          grep -v -f block-ips.lst "$GITHUB_WORKSPACE/temp.txt" >> block-domains.lst

      - name: Final processing
        run: |
          cd categories/Block
          # Единая сортировка и дедупликация
          sort -u block-ips.lst -o block-ips.lst
          sort -u block-domains.lst -o block-domains.lst

      - name: Generate hosts
        run: |
          cd categories/Block
          # Генерация hosts файла
          awk '{print "0.0.0.0 "$0}' block-ips.lst > ips.tmp
          awk '{print "0.0.0.0 "$0}' block-domains.lst > domains.tmp
          
          echo "# Auto-generated hosts" > hosts
          echo "" >> hosts
          echo "# IP addresses" >> hosts
          sort -u ips.tmp >> hosts
          echo "" >> hosts
          echo "# Domains" >> hosts
          sort -u domains.tmp >> hosts
          
          rm -f ips.tmp domains.tmp

      - name: Commit changes
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          cd categories/Block
          git add .
          git commit -m "Update block lists" || exit 0
          git push origin main
