name: Update Block Lists

on:
  schedule:
    - cron: '0 21 * * *'
  push:
    paths:
      - 'categories/Block/**.lst'
      - 'sources/sources-block.txt'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          mkdir -p categories/Block sources
          cd categories/Block
          touch block-ips.lst block-domains.lst
          rm -f ../temp.* *.tmp

      - name: Validate and fix entries
        run: |
          cd categories/Block
          # Сохраняем оригинальные записи перед очисткой
          cp block-ips.lst original-ips.bak
          cp block-domains.lst original-domains.bak
          
          # Очищаем только технические данные (комментарии, форматирование)
          sed -i -E '/^[[:space:]]*#/d; /^[[:space:]]*$/d' block-ips.lst block-domains.lst
          sed -i -E 's/^(0\.0\.0\.0|127\.0\.0\.1)[[:space:]]*//g' block-ips.lst block-domains.lst
          
          # Восстанавливаем пользовательские записи, удаляя только невалидные IP
          if [ -s block-ips.lst ]; then
            grep -E '^(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$' \
              original-ips.bak > block-ips.lst
          fi
          
          # Сохраняем оригинальные домены
          mv original-domains.bak block-domains.lst
          rm -f original-*.bak

      - name: Fetch external data
        run: |
          temp_file="$GITHUB_WORKSPACE/temp.txt"
          > "$temp_file"

          while IFS= read -r line || [ -n "$line" ]; do
            [[ "$line" =~ ^[[:space:]]*# || -z "$line" ]] && continue
            line=$(echo "$line" | xargs)

            echo "Processing URL: $line"
            curl -sSfL "$line" | \
              grep -v '^#' | \
              sed -E 's/^(0\.0\.0\.0|127\.0\.0\.1)[[:space:]]+//' | \
              grep -v '^[[:space:]]*$' >> "$temp_file" || true
          done < sources/sources-block.txt

      - name: Update lists
        run: |
          cd categories/Block
          
          # Добавляем новые IP (без перезаписи)
          grep -E '^(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])\.(25[0-5]|2[0-4][0-9]|1[0-9]{2}|[1-9]?[0-9])$' \
            "$GITHUB_WORKSPACE/temp.txt" >> block-ips.lst

          # Добавляем новые домены (исключая IP)
          grep -vFf block-ips.lst "$GITHUB_WORKSPACE/temp.txt" >> block-domains.lst

      - name: Final processing
        run: |
          cd categories/Block
          # Удаляем дубликаты и сортируем, сохраняя оригинальный порядок
          awk '!seen[$0]++' block-ips.lst > tmp && mv tmp block-ips.lst
          awk '!seen[$0]++' block-domains.lst > tmp && mv tmp block-domains.lst

          # Генерация hosts файла
          {
            echo "# Auto-generated hosts"
            echo -e "\n# IP addresses"
            awk '!seen[$0]++ {print "0.0.0.0 "$0}' block-ips.lst
            echo -e "\n# Domains"
            awk '!seen[$0]++ {print "0.0.0.0 "$0}' block-domains.lst
          } > hosts

      - name: Cleanup
        run: |
          rm -f "$GITHUB_WORKSPACE/temp.txt"

      - name: Commit changes
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add categories/Block/
          git commit -m "Update block lists (+preserve custom entries)" || exit 0
          git push origin main
