name: Update Block Lists

on:
  schedule:
    - cron: '0 0 * * *'  # Ежедневно в полночь UTC
  push:
    paths:
      - 'categories/Block/**.lst'
  workflow_dispatch:      # Ручной запуск

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Prepare environment
        run: |
          mkdir -p categories/Block
          cd categories/Block
          touch block-ips.lst block-domains.lst

      - name: Validate and fix entries
        id: validate
        run: |
          cd categories/Block
          # Строгая проверка IPv4 в доменном файле
          grep -E '^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$' block-domains.lst > ips_in_domains.tmp || true
          # Проверка доменов в IP-файле
          grep -v -E '^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$' block-ips.lst > domains_in_ips.tmp || true
          
          # Перемещение ошибочных записей
          if [ -s ips_in_domains.tmp ]; then
            cat ips_in_domains.tmp >> block-ips.lst
            grep -v -f ips_in_domains.tmp block-domains.lst > temp && mv temp block-domains.lst
          fi
          
          if [ -s domains_in_ips.tmp ]; then
            cat domains_in_ips.tmp >> block-domains.lst
            grep -v -f domains_in_ips.tmp block-ips.lst > temp && mv temp block-ips.lst
          fi
          
          rm -f *.tmp
          echo "fixed=1" >> $GITHUB_OUTPUT

      - name: Fetch external data
        run: |
          curl -s https://raw.githubusercontent.com/Ruddernation-Designs/Adobe-URL-Block-List/master/hosts  \
            | grep -v '^#' \
            | sed 's/^0.0.0.0 *//' \
            | grep -v '^$' > temp.txt

      - name: Update lists
        run: |
          cd categories/Block
          # Строгая валидация IPv4
          grep -E '^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$' \
            "$GITHUB_WORKSPACE/temp.txt" >> block-ips.lst
          # Все остальное считаем доменами
          grep -v -f block-ips.lst "$GITHUB_WORKSPACE/temp.txt" >> block-domains.lst

      - name: Final processing
        run: |
          cd categories/Block
          sort -u block-ips.lst -o block-ips.lst
          sort -u block-domains.lst -o block-domains.lst

      - name: Generate hosts
        run: |
          cd categories/Block
          # Генерация hosts файла
          awk '{print "0.0.0.0 "$0}' block-ips.lst > ips.tmp
          awk '{print "0.0.0.0 "$0}' block-domains.lst > domains.tmp
          
          echo "# Auto-generated hosts" > hosts
          echo "" >> hosts
          echo "# IP addresses" >> hosts
          sort -u ips.tmp >> hosts
          echo "" >> hosts
          echo "# Domains" >> hosts
          sort -u domains.tmp >> hosts
          
          rm -f ips.tmp domains.tmp

      - name: Commit changes
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          cd categories/Block
          git add .
          git commit -m "Update block lists" || exit 0
          git push origin main
