name: Create srs

on:
  push:
    branches: [ "main" ]
    paths:
      - cidr4/summary/raw.lst
      - domains.lst
  workflow_dispatch:

permissions:
  contents: write

jobs:
  wait-and-generate:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4.2.2

      - name: Wait until last commit is from actions-user
        run: |
          echo "Waiting for the last commit to be from 'actions-user'..."
          while true; do
            git fetch origin main
            AUTHOR=$(git log origin/main -1 --pretty=format:'%an')
            echo "Last commit author: $AUTHOR"
            if [ "$AUTHOR" = "actions-user" ]; then
              echo "Found commit from actions-user, continuing..."
              break
            fi
            echo "Not from actions-user, waiting 5 seconds..."
            sleep 5
          done

      - name: Pull latest changes
        run: |
          git pull origin main

      - name: Compile ruleset srs
        run: |
          docker run --rm \
          -v ${{ github.workspace }}:/app \
          itdoginfo/compilesrs:0.1.11 \
          python3 /app/scripts/convert.py

      - name: Move generated file to categories/SRS
        run: |
          mkdir -p ${{ github.workspace }}/categories/SRS
          mv ${{ github.workspace }}/domains-cidr4.srs ${{ github.workspace }}/categories/SRS/

      - name: Commit and push changes
        run: |
          git config --global user.name "actions-user"
          git config --global user.email "actions-user@users.noreply.github.com"
          git add categories/SRS/domains-cidr4.srs
          git commit -m "Update SRS ruleset on $(date +'%d.%m.%Y %H:%M')" || echo "No changes to commit"
          git push
