name: Create lists

on:
  push:
    branches: [ "main" ]
    paths:
      - cidr4/summary/raw.lst
      - domains.lst
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate-lists:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4.2.2
    - name: Compile ruleset srs
      run: |
         docker run --rm \
         -v ${{ github.workspace }}:/app/source \  # монтировать в другую папку
         itdoginfo/compilesrs:0.1.11

    - name: Push lists
      uses: EndBug/add-and-commit@v9
      with:
        add: 'compiled_rules.srs'
        author_name: GitHub Action
        author_email: githubaction@githubaction.com
        message: 'Update compiled_rules.srs'
        push: true

    - name: Set release tag
      run: echo "TAG_NAME=$(date +'%Y-%m-%d_%H-%M')" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v2.1.0
      with:
        files: |
          ${{ github.workspace }}/compiled_rules.srs
        tag_name: ${{ env.TAG_NAME }}
