name: Domain Comparison Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    paths:
      - 'domains.lst'
jobs:
  compare-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare directories
        run: |
          mkdir -p domain-categories
          cd domain-categories
          mkdir -p compared
          cd compared
          rm missing_domains.txt presence_domains.txt

      - name: Install dependencies
        run: sudo apt-get install -y wget grep

      - name: Download lists
        run: |
          wget -q -O inside-raw.lst https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-raw.lst
          wget -q -O domains.lst https://raw.githubusercontent.com/raywari/allow-domains-cidr4/main/domains.lst

      - name: Generate missing domains
        run: |
          while IFS= read -r domain; do
            # Проверяем все возможные варианты:
            # 1. Точное совпадение
            # 2. Совпадение как поддомен
            # 3. Совпадение родительского домена
            if ! grep -q -x "$domain" domains.lst && \
               ! grep -q "^\\.${domain#.}" domains.lst && \
               ! awk -v d="$domain" 'BEGIN {n=split(d,a,"."); 
                   for(i=2;i<=n;i++) {parent=a[i]; 
                   for(j=i+1;j<=n;j++) parent=parent"."a[j]; 
                   if ($0 ~ "^\\."parent"$") exit 0}} 
                   END {exit 1}' domains.lst; then
              echo "$domain" >> domain-categories/compared/missing_domains.txt
            fi
          done < inside-raw.lst

      - name: Generate presence domains
        run: |
          while IFS= read -r domain; do
            # Аналогичная проверка в обратную сторону
            if ! grep -q -x "$domain" inside-raw.lst && \
               ! grep -q "^\\.${domain#.}" inside-raw.lst && \
               ! awk -v d="$domain" 'BEGIN {n=split(d,a,"."); 
                   for(i=2;i<=n;i++) {parent=a[i]; 
                   for(j=i+1;j<=n;j++) parent=parent"."a[j]; 
                   if ($0 ~ "^\\."parent"$") exit 0}} 
                   END {exit 1}' inside-raw.lst; then
              echo "$domain" >> domain-categories/compared/presence_domains.txt
            fi
          done < domains.lst

      - name: Sort and unique lists
        run: |
          sort -u domain-categories/compared/missing_domains.txt -o domain-categories/compared/missing_domains.txt
          sort -u domain-categories/compared/presence_domains.txt -o domain-categories/compared/presence_domains.txt

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git pull origin main --rebase
          git add domain-categories/compared/*
          git commit -m "Update domain comparisons: $(date +%Y-%m-%d)" || echo "No changes"
          git push
