name: Domains Automation and Comparison

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    paths:
      - 'domains.lst'

jobs:
  process-and-compare-domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y wget grep

      # --- Сортировка domains.lst ---
      - name: Sort domains.lst
        run: |
          if [ -f domains.lst ]; then
            LC_COLLATE=C sort -f -u domains.lst -o domains.lst
            echo "domains.lst отсортирован."
          else
            echo "Файл domains.lst отсутствует."
            exit 1
          fi

      # --- Преобразование доменов с www в домены без www ---
      - name: Remove 'www.' from domains
        run: |
          if [ -f domains.lst ]; then
            sed -i 's/^www\.//g' domains.lst
            echo "'www.' удалено из доменов в domains.lst."
          else
            echo "Файл domains.lst отсутствует."
            exit 1
          fi

      # --- Фильтрация поддоменов (in-place) ---
      - name: Filter subdomains in-place
        run: |
          input_file="domains.lst"
          tmp=$(mktemp)
          mapfile -t domains < "$input_file"
          IFS=$'\n' sorted=($(printf '%s\n' "${domains[@]}" \
            | awk -F. '{print NF-1, $0}' \
            | sort -n \
            | cut -d' ' -f2-))
          unset IFS
          get_parents() {
            local domain=$1
            local parents=()
            local i=0
            while [[ $domain = *.* ]] && (( i < 99 )); do
              domain=${domain#*.}
              parents+=("$domain")
              ((i++))
            done
            echo "${parents[@]}"
          }
          declare -A kept
          for domain in "${sorted[@]}"; do
            parents=($(get_parents "$domain"))
            skip=false
            for p in "${parents[@]}"; do
              if [[ -n "${kept[$p]}" ]]; then
                skip=true
                break
              fi
            done
            if ! $skip; then
              echo "$domain" >> "$tmp"
              kept["$domain"]=1
            fi
          done
          sort -u "$tmp" -o "$input_file"
          rm "$tmp"
          echo "Поддомены до 99 уровней отфильтрованы (in-place)."

      # --- Генерация domains-nekobox.lst ---
      - name: Generate domains-nekobox.lst
        run: |
          input_file="domains.lst"
          output_file="domains-nekobox.lst"

          if [ -f "$input_file" ]; then
            sed 's/^/domain:/' "$input_file" > "$output_file"
            sort -u "$output_file" -o "$output_file"
            echo "Файл $output_file успешно создан."
          else
            echo "Файл $input_file не найден."
            exit 1
          fi

      # --- Сравнение доменов ---
      - name: Prepare and compare domain lists
        run: |
          # Определение URL-адресов списков
          INSIDE_RAW_URL="https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-raw.lst"
          COMMUNITY_URL="https://raw.githubusercontent.com/1andrevich/Re-filter-lists/refs/heads/main/community.lst"

          rm -f categories/Compared-Domains/missing-domains.txt categories/Compared-Domains/presence-domains.txt
          touch categories/Compared-Domains/missing-domains.txt categories/Compared-Domains/presence-domains.txt

          # Загрузка списков
          wget -q -O inside-raw.lst "$INSIDE_RAW_URL" || { echo "Ошибка загрузки inside-raw.lst"; exit 1; }
          wget -q -O community.lst "$COMMUNITY_URL" || { echo "Ошибка загрузки community.lst"; exit 1; }

          cp domains.lst my-domains.lst

          # Функция для проверки наличия родительского домена в списке
          has_parent_in_list() {
            local domain=$1
            local list=$2
            local parents=()
            local i=0
            while [[ $domain = *.* ]] && (( i < 99 )); do
              domain=${domain#*.}
              parents+=("$domain")
              ((i++))
            done
            for p in "${parents[@]}"; do
              if grep -q -x "$p" "$list"; then
                return 0
              fi
            done
            return 1
          }

          # Сравнение с inside-raw.lst (missing)
          while IFS= read -r domain; do
            if ! grep -q -x "$domain" my-domains.lst && \
               ! has_parent_in_list "$domain" my-domains.lst; then
              echo "$domain" >> categories/Compared-Domains/missing-domains.txt
            fi
          done < inside-raw.lst

          # Сравнение с community.lst (missing)
          while IFS= read -r domain; do
            if ! grep -q -x "$domain" my-domains.lst && \
               ! has_parent_in_list "$domain" my-domains.lst; then
              echo "$domain" >> categories/Compared-Domains/missing-domains.txt
            fi
          done < community.lst

          # Сравнение с inside-raw.lst (presence)
          while IFS= read -r domain; do
            if ! grep -q -x "$domain" inside-raw.lst && \
               ! has_parent_in_list "$domain" inside-raw.lst; then
              echo "$domain" >> categories/Compared-Domains/presence-domains.txt
            fi
          done < my-domains.lst

          # Сравнение с community.lst (presence)
          while IFS= read -r domain; do
            if ! grep -q -x "$domain" community.lst && \
               ! has_parent_in_list "$domain" community.lst; then
              echo "$domain" >> categories/Compared-Domains/presence-domains.txt
            fi
          done < my-domains.lst

          # Сортировка и устранение дубликатов
          sort -u categories/Compared-Domains/missing-domains.txt -o categories/Compared-Domains/missing-domains.txt
          sort -u categories/Compared-Domains/presence-domains.txt -o categories/Compared-Domains/presence-domains.txt

          # Удаление доменов с TLD .ua
          grep -v '\.ua$' categories/Compared-Domains/missing-domains.txt > tmp.txt && mv tmp.txt categories/Compared-Domains/missing-domains.txt
          grep -v '\.ua$' categories/Compared-Domains/presence-domains.txt > tmp.txt && mv tmp.txt categories/Compared-Domains/presence-domains.txt

          echo "Сравнение доменных списков завершено, домены с TLD .ua удалены."

      # --- Генерация domains-without-yt.lst ---
      - name: Generate domains-without-yt.lst excluding YouTube domains
        run: |
          input_file="domains.lst"
          exclude_file="categories/Services/youtube/youtube-domains.lst"
          output_file="domains-without-yt.lst"

          if [ -f "$input_file" ]; then
            grep -vxFf "$exclude_file" "$input_file" | sort -u > "$output_file"
            echo "Файл $output_file успешно создан."
          else
            echo "Файл $input_file не найден."
            exit 1
          fi

      # --- Коммит для .lst файлов ---
      - name: Commit and push .lst changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add domains.lst domains-nekobox.lst domains-without-yt.lst
          git commit -m "Обновление доменных .lst файлов" || echo "Нет изменений для коммита"
          git push

      # --- Коммит для Compared-Domains ---
      - name: Commit and push Compared-Domains changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add categories/Compared-Domains/*
          git commit -m "Автоматическое сравнение: $(date +'%Y-%m-%d')" || echo "Нет изменений для коммита"
          git push
