name: Domains for Nekobox

on:
  push:
    paths:
      - 'domains.lst'
  workflow_dispatch:

jobs:
  transform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Transform domains
        run: |
          input_file="domains.lst"
          output_file="domains_nekobox.lst"

          if [ ! -f "$input_file" ]; then
            echo "Файл $input_file не найден."
            exit 1
          fi

          sed 's/^/domain:/' "$input_file" > "$output_file"

          echo "Файл $output_file успешно создан."

          sort -u "$output_file"

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add domains_nekobox.lst
          git commit -m "Update domains_nekobox.lst from domains.lst" || echo "No changes to commit"
          git push
