name: Domains Automation and Comparison

on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
  push:
    paths:
      - 'domains.lst'
      - 'sources/sources-domains.txt'
      - '.github/workflows/domains-automation.yml'

jobs:
  process-and-compare-domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt-get install -y wget grep moreutils

      - name: Clean domains.lst
        run: |
          sed -i '/^[[:space:]]*#/d; /^;/d; /^\/\//d; /^[[:space:]]*--/d' domains.lst
          sed -i 's/^full://g; s|^https\?://||g; s|^//||g' domains.lst
          sed -i 's|/.*$||g; s|:.*$||g; s|^www[2-9]\?\.||g' domains.lst
          sed -i 's/^[[:space:]]*//; s/[[:space:]]*$//; /^$/d' domains.lst

      - name: Sort domains.lst
        run: LC_COLLATE=C sort -f -u domains.lst -o domains.lst

      - name: Filter subdomains in domains.lst
        run: |
          get_parents() {
            local d=$1
            while [[ $d == *.* ]]; do
              d=${d#*.}
              echo "$d"
            done
          }
          mapfile -t all < domains.lst
          IFS=$'\n' sorted=($(printf '%s\n' "${all[@]}" |
            awk -F. '{print NF-1, $0}' | sort -n | cut -d' ' -f2-))
          declare -A keep; > filtered.txt
          for dom in "${sorted[@]}"; do
            skip=
            for p in $(get_parents "$dom"); do
              [[ ${keep[$p]} ]] && { skip=1; break; }
            done
            [[ $skip ]] || { echo "$dom" >> filtered.txt; keep[$dom]=1; }
          done
          sort -u filtered.txt -o domains.lst
          rm filtered.txt

      - name: Generate NekoBox list
        run: sed 's/^/domain:/' domains.lst | sort -u > domains-nekobox.lst

      - name: Compare with external sources
        run: |
          normalize() {
            sed -i 's/^full://g; s|^https\?://||g; s|^//||g' "$1"
            sed -i 's|/.*$||g; s|:.*$||g; s|^www[2-9]\?\.||g' "$1"
            sed -i 's/^[[:space:]]*//; s/[[:space:]]*$//; /^$/d' "$1"
            sort -u "$1" -o "$1"
          }

          # load parent domains set
          declare -A PARENT
          while read -r d; do PARENT["$d"]=1; done < domains.lst

          mkdir -p categories/Compared-Domains
          cp domains.lst my-domains.lst
          normalize my-domains.lst

          declare -A SOURCES
          while IFS= read -r line; do
            [[ "$line" =~ ^#|^$ ]] && continue
            url=${line// /}
            name=$(basename "$url" | sed 's/\.[^.]*$//')
            SOURCES["$name"]="$url"
          done < sources/sources-domains.txt

          for name in "${!SOURCES[@]}"; do
            url=${SOURCES[$name]}
            wget -qO "${name}.lst" "$url" || continue
            normalize "${name}.lst"

            # filter out any subdomain whose parent is in domains.lst
            get_parents() {
              local d=$1
              while [[ $d == *.* ]]; do
                d=${d#*.}
                echo "$d"
              done
            }
            > filtered_"$name".lst
            while read -r d; do
              skip=
              for p in $(get_parents "$d"); do
                [[ ${PARENT[$p]} ]] && { skip=1; break; }
              done
              [[ $skip ]] || echo "$d" >> filtered_"$name".lst
            done < "${name}.lst"
            mv filtered_"$name".lst "${name}.lst"

            # compare, excluding .ua TLD
            comm -23 <(sort "${name}.lst") <(sort my-domains.lst) | \
              grep -v '\.ua$' > "missing_${name}.txt"
            comm -13 <(sort "${name}.lst") <(sort my-domains.lst) | \
              grep -v '\.ua$' > "presence_${name}.txt"
          done

          {
            for name in "${!SOURCES[@]}"; do
              echo "### Missing in $name ###"
              cat "missing_${name}.txt"
              echo
            done
          } > categories/Compared-Domains/missing-domains.txt

          {
            for name in "${!SOURCES[@]}"; do
              echo "### Present only in $name ###"
              cat "presence_${name}.txt"
              echo
            done
          } > categories/Compared-Domains/presence-domains.txt

      - name: Generate domains without YouTube
        run: |
          yt="categories/Services/youtube/youtube-domains.lst"
          [[ -f "$yt" && -f domains.lst ]] && \
            grep -vxFf "$yt" domains.lst > domains-without-yt.lst

      - name: Commit and push .lst changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          for f in domains.lst domains-nekobox.lst domains-without-yt.lst; do
            [[ -f $f ]] && git add "$f"
          done
          git commit -m "Обновление доменных .lst файлов" || echo "Нет изменений для коммита"
          git push origin main

      - name: Commit and push Compared-Domains changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          for f in categories/Compared-Domains/missing-domains.txt categories/Compared-Domains/presence-domains.txt; do
            [[ -f $f ]] && git add "$f"
          done
          git commit -m "Автоматическое сравнение: $(date +'%Y-%m-%d')" || echo "Нет изменений для коммита"
          git push origin main