name: Domain Comparison Workflow
on:
  workflow_dispatch:
  schedule:
    - cron: '0 10 * * *'
jobs:
  compare-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare directories
        run: |
          mkdir -p domain-categories/compared
          rm -f domain-categories/compared/missing_domains.txt domain-categories/compared/presence_domains.txt

      - name: Install dependencies
        run: sudo apt-get install -y wget grep

      - name: Download lists
        run: |
          wget -q -O inside-raw.lst https://raw.githubusercontent.com/itdoginfo/allow-domains/main/Russia/inside-raw.lst
          wget -q -O domains.lst https://raw.githubusercontent.com/raywari/allow-domains-cidr4/main/domains.lst

      - name: Generate missing domains
        run: |
          while IFS= read -r domain; do
            covered=0
            suffix=$domain
            while [ -n "$suffix" ]; do
              if grep -q -x "$suffix" domains.lst; then
                covered=1
                break
              fi
              suffix=${suffix#*.}
            done
            if [ $covered -eq 0 ]; then
              echo "$domain" >> domain-categories/compared/missing_domains.txt
            fi
          done < inside-raw.lst

      - name: Generate presence domains
        run: |
          while IFS= read -r domain; do
            if ! grep -q -x "$domain" inside-raw.lst; then
              echo "$domain" >> domain-categories/compared/presence_domains.txt
            fi
          done < domains.lst

      - name: Sort and unique lists
        run: |
          sort -u domain-categories/compared/missing_domains.txt -o domain-categories/compared/missing_domains.txt
          sort -u domain-categories/compared/presence_domains.txt -o domain-categories/compared/presence_domains.txt

      - name: Commit results
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add domain-categories/compared/*
          git commit -m "Update domain comparisons: $(date +%Y-%m-%d)" || echo "No changes"
          git push
