name: Domains list automation

on:
  workflow_dispatch:
  push:
    paths:
      - 'domains.lst'

jobs:
  process-domains:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Sort domains.lst
        run: |
          if [ -f domains.lst ]; then
            LC_COLLATE=C sort -f -u domains.lst -o domains.lst
            echo "domains.lst отсортирован."
          else
            echo "Файл domains.lst отсутствует."
            exit 1
          fi

      - name: Transform domains.lst to domains_nekobox.lst
        run: |
          input_file="domains.lst"
          output_file="domains_nekobox.lst"

          if [ ! -f "$input_file" ]; then
            echo "Файл $input_file не найден."
            exit 1
          fi

          sed 's/^/domain:/' "$input_file" > "$output_file"
          sort -u "$output_file" -o "$output_file"

          echo "Файл $output_file успешно создан."

      - name: Commit changes if any
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add domains.lst domains_nekobox.lst
          git commit -m "Автообновление domains.lst и domains_nekobox.lst" || echo "Нет изменений для коммита"
          git push
