name: Domains Automation

on:
  schedule:
    - cron: '0 10 * * *'
  push:
    paths:
      - 'domains.lst'
      - '.scripts/sources/**'
      - 'categories/**'
      - '.scripts/config/**'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  process-domains:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests aiohttp aiofiles toml

      - name: Run parsing-domains script
        run: python .scripts/parsing-domains.py

      - name: Run process-domains script
        run: python .scripts/process-domains.py

      - name: Commit and push domains/compare results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add domains.lst domains-without-yt.lst categories/Compared-Domains categories/Services
          git commit -m "Update domains lists" || echo "No changes"
          git push origin HEAD:main
          git pull origin HEAD:main

      - name: Run process-subnets script
        run: python .scripts/process-subnets.py

      - name: Commit and push CIDR changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add categories/CIDRs/*
          git commit -m "Update CIDR lists" || echo "No changes"
          git push origin HEAD:main
          git pull origin HEAD:main

      - name: Run generate-srs script
        run: python .scripts/generate-srs.py

      - name: Commit and push SRS ruleset
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add categories/Rulesets/domains-cidr4.srs
          git commit -m "Update SRS ruleset" || echo "No changes"
          git push origin HEAD:main
          git pull origin HEAD:main

      - name: Run generate-routing-config script
        run: python .scripts/generate-routing-config.py

      - name: Commit and push routing config
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add categories/Rulesets/nekoray-mahdi.json
          git commit -m "Update routing config" || echo "No changes"
          git push origin HEAD:main
          git pull origin HEAD:main

      - name: Run update-block-lists script
        run: python .scripts/update-block-lists.py

      - name: Commit and push block lists
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add categories/Block/**
          git commit -m "Update block lists" || echo "No changes"
          git push origin HEAD:main
          git pull origin HEAD:main

      - name: Run generate-sing-box-rules script
        run: python .scripts/generate-sing-box-rules.py

      - name: Commit and push sing-box-rules
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add categories/Rulesets/sing-box-rules/**
          git commit -m "Update sing-box-rules" || echo "No changes"
          git push origin HEAD:main
          git pull origin HEAD:main
